/* Finance + expense UI trust boundaries. Simulated transport; no banking/provider call. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {webcrypto}=require('node:crypto'),{parseHTML}=require('linkedom');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'web/app.js'),'utf8');
let count=0;const passed=label=>console.log(`PASS finance ${++count}: ${label}`);
const invoice={id:'invoice-1',task_id:'task-1',task_version:3,version:1,direction:'receivable',invoice_number:'SYNTH-01',supplier:'Demo Supplier',customer:'Client <img src=x onerror=alert(1)>',total_amount:'120.00',currency:'EUR',remaining_amount:'120.00',paid_amount:'0.00',due_date:'2026-11-01',payment_status:'unpaid',disputed:false,assignment_status:'none'};
const transaction={id:'tx-1',account_ref:'test-account',transaction_id:'bank-id-1',date:'2026-10-02',amount:'60.00',currency:'EUR',reference:'SYNTH-01 <img src=x onerror=alert(1)>',remaining_amount:'60.00',version:2};
const task={id:'task-1',title:'Facture synthétique',skill_id:'invoice-check',country:'FR',status:'ready',version:3,payload:{invoice_number:'SYNTH-02',supplier:'Demo',customer:'Test',total_amount:'120.00',currency:'EUR',due_date:'2026-11-01'}};
async function makeUI(role='operator') {
  const {window,document}=parseHTML(fs.readFileSync(path.join(root,'web/index.html'),'utf8'));
  for(const dialog of document.querySelectorAll('dialog')){Object.defineProperty(dialog,'open',{get(){return this.hasAttribute('open');}});dialog.showModal=function(){this.setAttribute('open','');};dialog.close=function(){this.removeAttribute('open');};}
  Object.defineProperty(window.HTMLInputElement.prototype,'checked',{configurable:true,get(){return this.hasAttribute('checked');},set(v){v?this.setAttribute('checked',''):this.removeAttribute('checked');}});
  Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){const o=this.querySelector('option[selected]')||this.querySelector('option');return o?.getAttribute('value')||'';},set(v){for(const o of this.querySelectorAll('option'))o.getAttribute('value')===String(v)?o.setAttribute('selected',''):o.removeAttribute('selected');}});
  const requests=[];let handler=null,serverRole=role;
  const reply=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
  const session=()=>({authenticated:!!serverRole,user:serverRole?{username:'synthetic-user',role:serverRole}:null,scope:'production_single_client',csrf_token:'synthetic-csrf',client:{name:'Synthetic company'},capabilities:{finance_read:!!serverRole,finance_write:serverRole!=='reader'&&!!serverRole,finance_export:serverRole==='admin',finance_simulate:serverRole!=='reader'&&!!serverRole,documents_read:!!serverRole,documents_create_task:serverRole!=='reader'&&!!serverRole,create:serverRole!=='reader'&&!!serverRole,update:serverRole!=='reader'&&!!serverRole}});
  const preview={preview_digest:'sha256-synthetic',row_count:1,new_count:1,duplicate_count:0,rows:[{...transaction,state:'new'}]};
  const fetch=async(url,options={})=>{
    const body=typeof options.body==='string'?JSON.parse(options.body):options.body;requests.push({url,options,body});
    assert.equal(options.credentials,'same-origin');assert.equal(options.cache,'no-store');
    if(options.method==='POST')assert.equal(options.headers['X-CSRF-Token'],'synthetic-csrf');
    if(handler){const custom=await handler(url,options,body);if(custom)return custom;}
    if(url==='/api/session')return reply(session());if(!serverRole)return reply({error:{code:'auth_required',message:'Session expirée'}},401);
    if(url==='/api/logout'){serverRole=null;return reply(session());}
    if(url==='/api/dashboard')return reply({tasks:[task],metrics:{total:1}});
    if(url==='/api/skills')return reply({skills:[{id:'invoice-check',name:'Contrôle facture',status:'implemented'},{id:'expense-review',name:'Note de frais',status:'implemented'}]});
    if(url==='/api/health')return reply({mode:'offline'});
    if(url==='/api/tasks/task-1')return reply({task,events:[]});
    if(url==='/api/finance/summary')return reply({by_currency:[{currency:'EUR',receivable_remaining:'120.00',payable_remaining:'0.00',receivable_overdue:'0.00',payable_overdue:'0.00'},{currency:'USD',receivable_remaining:'250.00',payable_remaining:'0.00',receivable_overdue:'0.00',payable_overdue:'0.00'}]});
    if(url==='/api/finance/invoices')return reply({invoices:[invoice]});
    if(url==='/api/finance/bank-transactions')return reply({transactions:[transaction]});
    if(url==='/api/finance/allocations')return reply({allocations:[]});
    if(url==='/api/finance/suggestions')return reply({suggestions:[{invoice_id:'invoice-1',transaction_id:'tx-1',amount:'60.00',invoice_version:1,transaction_version:2,reason:'reference_partial'}],manual_only:[]});
    if(url==='/api/finance/bank/preview')return reply({preview});
    if(url==='/api/finance/bank/import')return reply({import:{created:1,duplicates:0}});
    if(url==='/api/finance/allocations/confirm')return reply({allocation:{id:'allocation-1'}});
    if(url==='/api/finance/invoices/register')return reply({invoice});
    if(url==='/api/finance/factoring/simulate')return reply({simulation:{invoice_id:'invoice-1',currency:'EUR',nominal:'120.00',advance:'96.00',reserve:'24.00',fees:'1.20',interest:'0.48',total_cost:'1.68',net_cash:'94.32',days:30,day_basis:360,advance_rate:'80.00',fee_rate:'1.00',annual_interest_rate:'6.00',fixed_fee:'0.00',funding_date:'2026-10-02',maturity_date:'2026-11-01',assumptions:['Synthetic <img src=x onerror=alert(1)>']}});
    if(url==='/api/documents')return reply({documents:[],enabled:true});
    if(url==='/api/documents/doc-1/reverify-expense')return reply({task:{...task,status:'new'},document:{id:'doc-1'}});
    throw new Error('Unexpected request '+url);
  };
  const context=vm.createContext({window,document,console,FormData,crypto:webcrypto,AbortController,Blob,URL,location:{hash:'',origin:'https://synthetic.test'},navigator:{clipboard:{writeText:async()=>{}}},fetch,setTimeout:(fn,ms)=>{const t=setTimeout(fn,ms);t.unref();return t;},clearTimeout});
  const run=code=>vm.runInContext(code,context);await run(source);
  const set=(id,value)=>{const element=document.querySelector('#'+id);assert.ok(element,id);typeof value==='boolean'?element.checked=value:element.value=value;return element;};
  return {run,document,window,requests,reply,set,setHandler:fn=>handler=fn,setRole:role=>serverRole=role};
}
(async()=>{
  const ui=await makeUI();ui.run("state.page='finance'");await ui.run('loadFinance()');
  assert.equal(ui.document.querySelector('#finance-nav').hidden,false);assert.equal(ui.document.querySelectorAll('.finance-balance').length,2);assert.equal(ui.document.querySelectorAll('img').length,0);assert.match(ui.document.body.textContent,/120.00 EUR/);assert.match(ui.document.body.textContent,/250.00 USD/);assert.equal(ui.requests.filter(r=>r.options.method==='POST').length,0);
  passed('Read-only load separates currencies, escapes invoice text and performs no mutation');

  const reader=await makeUI('reader');reader.run("state.page='finance'");await reader.run('loadFinance()');reader.run("state.finance.tab='bank';renderFinance()");assert.equal(reader.document.querySelector('#finance-bank-form'),null);assert.equal(reader.document.querySelector('[data-action=finance-allocate]'),null);const before=reader.requests.length;await reader.run('openFinanceRegister();openFinanceAllocation();openFinanceFactoring();openFinanceAssignment();exportFinance({});previewBank({});importBank({})');assert.equal(reader.requests.length,before);reader.run("state.finance.tab='factoring';renderFinance()");assert.equal(reader.document.querySelector('[data-action=finance-factor]'),null);
  passed('Reader sees finance data but controls and direct handlers deny writes, simulation and export');

  ui.run('state.finance.invoices=[]');await ui.run('openFinanceRegister()');assert.equal(ui.document.querySelector('#finance-opening-paid').value,'');assert.equal(ui.document.querySelector('#finance-opening-confirmed').checked,false);ui.set('finance-register-task','task-1');await ui.run("loadFinanceSource('task-1')");await ui.run("registerFinanceInvoice(document.querySelector('#finance-register-form'))");assert.match(ui.document.querySelector('#finance-form-error').textContent,/Confirmez/);ui.set('finance-direction','receivable');ui.set('finance-opening-paid','0,00');ui.set('finance-opening-date','2026-10-01');ui.set('finance-disputed','unknown');ui.set('finance-register-evidence','Synthetic opening proof');ui.set('finance-opening-confirmed',true);await ui.run("registerFinanceInvoice(document.querySelector('#finance-register-form'))");const registration=ui.requests.find(r=>r.url.endsWith('/register')).body;assert.equal(registration.task_version,3);assert.equal(registration.disputed,'unknown');assert.equal(registration.opening_paid_amount,'0.00');assert.equal(registration.opening_confirmed,true);
  passed('Register requires inspected ready source version and explicit opening balance; unknown dispute remains unknown');

  ui.run("state.finance.tab='bank';renderFinance()");ui.set('finance-account','account-1');ui.set('finance-csv','transaction_id,date,amount,currency,reference\nT1,2026-10-02,60.00,EUR,SYNTH-01');await ui.run("previewBank(document.querySelector('#finance-bank-form'))");assert.equal(ui.requests.some(r=>r.url.endsWith('/bank/import')),false);assert.equal(ui.document.querySelector('#finance-import-confirmed').checked,false);assert.equal(ui.document.querySelectorAll('img').length,0);await ui.run("importBank(document.querySelector('[data-action=finance-import]'))");assert.match(ui.document.querySelector('#finance-bank-error').textContent,/confirmez/);ui.set('finance-import-confirmed',true);await ui.run("importBank(document.querySelector('[data-action=finance-import]'))");assert.equal(ui.requests.find(r=>r.url.endsWith('/bank/import')).body.preview_digest,'sha256-synthetic');assert.equal(ui.document.querySelector('#finance-csv').value,'');assert.equal(ui.run('state.finance.previewInput'),null);
  passed('CSV preview never imports automatically; confirmation binds exact digest and clears raw content after import');

  ui.set('finance-csv','changed csv');let release;ui.setHandler(async url=>url.endsWith('/bank/preview')?new Promise(resolve=>release=()=>resolve(ui.reply({preview:{row_count:0,rows:[]}}))):null);const pending=ui.run("previewBank(document.querySelector('#finance-bank-form'))");ui.set('finance-csv','newer csv').dispatchEvent(new ui.window.Event('input',{bubbles:true}));release();await pending;assert.equal(ui.run('state.finance.preview'),null);assert.equal(ui.document.querySelector('#finance-bank-preview').textContent,'');ui.setHandler(null);
  passed('Editing CSV invalidates both the preview and a delayed response from the previous contents');

  ui.run('openFinanceAllocation(state.finance.suggestions[0])');ui.set('finance-allocation-evidence','Synthetic reference verified');await ui.run("confirmFinanceAllocation(document.querySelector('#finance-allocation-form'))");assert.match(ui.document.querySelector('#finance-form-error').textContent,/Confirmez/);ui.set('finance-allocation-confirmed',true);let attempts=0;ui.setHandler(async url=>{if(url.endsWith('/allocations/confirm')&&++attempts<3)throw new Error('Response lost');return null;});await ui.run("confirmFinanceAllocation(document.querySelector('#finance-allocation-form'))");await ui.run("confirmFinanceAllocation(document.querySelector('#finance-allocation-form'))");const lost=ui.requests.filter(r=>r.url.endsWith('/allocations/confirm'));assert.equal(lost[0].body.idempotency_key,lost[1].body.idempotency_key);assert.equal(lost[0].body.invoice_version,1);assert.equal(lost[0].body.transaction_version,2);ui.set('finance-allocation-amount','50.00');await ui.run("confirmFinanceAllocation(document.querySelector('#finance-allocation-form'))");const changed=ui.requests.filter(r=>r.url.endsWith('/allocations/confirm'));assert.notEqual(changed[1].body.idempotency_key,changed[2].body.idempotency_key);ui.setHandler(null);
  passed('Partial allocation is explicit and versioned; identical lost-response retries retain an idempotency key');

  ui.run('openFinanceAllocation(state.finance.suggestions[0])');ui.set('finance-allocation-evidence','proof');ui.set('finance-allocation-confirmed',true);ui.setHandler(async url=>url.endsWith('/allocations/confirm')?ui.reply({error:{code:'version_conflict',message:'Source modifiée'}},409):null);await ui.run("confirmFinanceAllocation(document.querySelector('#finance-allocation-form'))");assert.match(ui.document.querySelector('#finance-form-error').textContent,/Fermez/);assert.equal(ui.document.querySelector('#finance-allocation-form button[type=submit]').disabled,true);ui.setHandler(null);ui.run("document.querySelector('#finance-dialog').close()");
  passed('A stale allocation reloads current balances and disables retry until a fresh review');

  ui.run('openFinanceFactoring()');for(const id of ['finance-advance-rate','finance-fee-rate','finance-interest-rate','finance-fixed-fee'])assert.equal(ui.document.querySelector('#'+id).value,'');ui.set('finance-factor-invoice','invoice-1');ui.set('finance-funding-date','2026-10-02');ui.set('finance-advance-rate','80');ui.set('finance-fee-rate','1');ui.set('finance-interest-rate','6');ui.set('finance-fixed-fee','0');ui.set('finance-day-basis','360');await ui.run("simulateFactoring(document.querySelector('#finance-factoring-form'))");assert.match(ui.document.querySelector('#finance-simulation').textContent,/94.32 EUR/);assert.match(ui.document.querySelector('#finance-simulation').textContent,/Aucun financeur consulté/);assert.equal(ui.document.querySelectorAll('img').length,0);
  passed('Factoring has no assumed prices; it displays backend results and explicit non-offer wording');

  ui.run("state.documentDetail={id:'doc-1',filename:'Synthetic receipt',status:'extracted',extraction_version:1,extraction:{candidates:{merchant:{value:'Cafe <img src=x>',page:1,quote:'Cafe'},expense_date:{value:'2026-10-01',page:1,quote:'Date'},total_amount:{value:'24.00',page:1,quote:'Total'},currency:{value:'EUR',page:1,quote:'EUR'}},pages:[]}};renderDocumentDetail()");ui.set('document-skill','expense-review');ui.run('renderDocumentFields()');assert.equal(ui.document.querySelector('#document-field-invoice_number'),null);assert.equal(ui.document.querySelector('#document-field-merchant').value,'Cafe <img src=x>');for(const field of ['paid_by_company','reimbursed','business_only','policy_confirmed','payment_confirmed'])assert.equal(ui.document.querySelector('#document-field-'+field).value,'');ui.set('document-verify-total_amount',true);ui.set('document-human-verified',true);ui.set('document-field-total_amount','25.00').dispatchEvent(new ui.window.Event('input',{bubbles:true}));assert.equal(ui.document.querySelector('#document-verify-total_amount').checked,false);assert.equal(ui.document.querySelector('#document-human-verified').checked,false);assert.equal(ui.document.querySelectorAll('img').length,0);
  passed('Receipt review uses expense fields, leaves human assertions unknown and invalidates confirmation on edit');

  ui.run("state.documentDetail.task_id='task-1';state.documentLinkedTask={id:'task-1',skill_id:'expense-review',version:7,payload:{merchant:'Cafe',expense_date:'2026-10-01',total_amount:'25.00',currency:'EUR'}};renderDocumentDetail()");await ui.run("reverifyExpenseDocument(document.querySelector('#document-reverify-form'))");assert.match(ui.document.querySelector('#document-reverify-error').textContent,/quatre/);for(const field of ui.document.querySelectorAll('[data-reverify-field]'))field.checked=true;ui.set('document-reverify-confirmed',true);await ui.run("reverifyExpenseDocument(document.querySelector('#document-reverify-form'))");const reviewed=ui.requests.find(r=>r.url.endsWith('/reverify-expense')).body;assert.equal(reviewed.task_version,7);assert.equal(reviewed.extraction_version,1);assert.deepEqual(reviewed.verified_fields,['merchant','expense_date','total_amount','currency']);assert.equal(ui.requests.some(r=>r.url.endsWith('/analyze')||r.url.endsWith('/review')),false);
  passed('Receipt reconfirmation requires four checks and exact versions; it does not auto-analyze or approve');

  ui.run("document.querySelector('#detail-dialog').close();state.page='finance';state.finance.tab='bank';renderFinance()");ui.set('finance-csv','SECRET RAW CSV');ui.run("state.finance.previewInput={csv_text:'SECRET RAW CSV'};openFinanceAllocation()");ui.set('finance-allocation-evidence','SECRET UNSENT PROOF');await ui.run('logout()');assert.equal(ui.run('state.finance.invoices.length'),0);assert.equal(ui.run('state.finance.previewInput'),null);assert.equal(ui.run('state.finance.simulation'),null);assert.equal(ui.document.querySelector('#finance-dialog').innerHTML,'');assert.equal(ui.document.body.textContent.includes('SECRET'),false);
  passed('Logout purges invoices, raw CSV, simulation and unsent finance dialogs');

  const race=await makeUI();let finish;race.setHandler(async url=>url.endsWith('/finance/summary')?new Promise(resolve=>finish=()=>resolve(race.reply({by_currency:[]}))):null);const loading=race.run('loadFinance()');await race.run('logout()');finish();await loading;assert.equal(race.run('state.finance.loaded'),false);assert.equal(race.run('state.finance.invoices.length'),0);
  passed('Late finance responses from an old session cannot restore sensitive records');
  console.log(`${count} finance DOM scenarios passed; synthetic transport, no visual or live banking claim.`);
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
